name: Build and changelog
on: 
  workflow_dispatch:

jobs:

  message:
    name: Changelog and message
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
        tag_prefix: v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      with:
        fromTag: ${{ steps.previoustag.outputs.tag }}
        toTag: ${{ steps.tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Format changelog for the message
      id: format_changelog
      uses: kaskar2008/action-release-to-telegram@v0.0.6
      with:
        template: .github/tg-message.mustache
        service-name: ATA Updates
        tag: ${{steps.tag.outputs.tag}}
        changelog: ${{ steps.github_release.outputs.changelog }}

    - name: Send technical release message to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: ${{ steps.format_changelog.outputs.message }}
        format: 'markdown'


  build:
    environment: NuGet

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  
                            
    env:
      Solution_Name: ATA-GUI.sln
      
    steps:
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Prepare package
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="ATA-GUI_$tag"
        release_path="D:/a/ATA-GUI/ATA-GUI/ATA-GUI/bin/Release/"
        7z a -tzip "${release_name}.zip" "${release_path}Newtonsoft.Json.dll" "${release_path}ATA-GUI.exe" "${release_path}DotNetZip.dll" "D:/a/ATA-GUI/ATA-GUI/LICENSE"
      
  
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: ATA-GUI_*
        name: ${{steps.previoustag.outputs.tag}}
        tag: ${{steps.previoustag.outputs.tag}}
        token: ${{ secrets.GITHUB_TOKEN }}
