name: telegram message
on:
  release:
    types: [published]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Read changelog
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: D:/a/ATA-GUI/CHANGELOG.md
    
    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: "Download: \nhttps://github.com/msartore/ATA-GUI/releases/latest/download/ATA-GUI_${steps.previoustag.outputs.tag}.zip \nChangelog: /n${{ steps.package.outputs.content }}"
